# Generated by Django 2.0.2 on 2020-02-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
