# Generated by Django 2.0.2 on 2020-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0004_auto_20200227_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pre_post',
            field=models.BooleanField(default=True),
        ),
    ]
