# Generated by Django 3.0.3 on 2020-03-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0005_image_pre_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image',
            name='flood_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='image',
            name='pair_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
