# Generated by Django 3.0.3 on 2020-03-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
