# Generated by Django 3.0.3 on 2020-03-19 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0006_auto_20200319_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='flood_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
