# Generated by Django 3.0.3 on 2020-03-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0009_auto_20200319_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='filepath',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
