# Generated by Django 3.0.3 on 2020-04-10 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterlogged', '0009_image_pair_attempted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=11)),
                ('display_name', models.CharField(default='', max_length=75)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_login_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
