# Generated by Django 3.0.3 on 2020-03-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0010_auto_20200319_0235'),
        ('waterlogged', '0009_image_pair_attempted'),
    ]

    operations = [
    ]
