# Generated by Django 3.0.3 on 2020-04-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0012_remove_profile_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login_date',
        ),
    ]
