# Generated by Django 3.0.3 on 2020-04-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0014_auto_20200410_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
