# Generated by Django 3.0.3 on 2020-04-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0016_auto_20200409_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='image',
            field=models.ImageField(upload_to='temp_images'),
        ),
    ]
