# Generated by Django 3.0.3 on 2020-04-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0017_auto_20200410_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
