# Generated by Django 3.0.3 on 2020-04-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0020_auto_20200410_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='longitude',
        ),
    ]
