# Generated by Django 3.0.3 on 2020-04-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0022_auto_20200411_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filepath',
            field=models.CharField(default='', max_length=300),
        ),
    ]
