# Generated by Django 3.0.3 on 2020-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0024_merge_20200414_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
