# Generated by Django 2.0.2 on 2020-02-11 15:19

from django.db import migrations

def create_data(apps, schema_editor):
    Image = apps.get_model('waterlogged', "Image")
    Image(name = "pic1", long = "0", latt = "0", paired_id = "2", filePath = "")


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0002_auto_20200207_0304'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
