# Generated by Django 2.0.2 on 2020-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0003_waterlogged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='image',
            name='latt',
        ),
        migrations.RemoveField(
            model_name='image',
            name='long',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='paired_id',
        ),
        migrations.AddField(
            model_name='image',
            name='approved_by_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='image',
            name='filepath',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='image',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='pair_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='user_uploaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
