# Generated by Django 3.0.3 on 2020-03-19 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0007_image_flood_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='flood_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
