# Generated by Django 3.0.3 on 2020-04-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
    ]
