# Generated by Django 3.0.3 on 2020-03-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0011_merge_20200320_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='address',
            field=models.CharField(default='x', max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(default='x', max_length=300),
        ),
    ]
