# Generated by Django 3.0.3 on 2020-04-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0018_auto_20200410_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='longitude',
        ),
    ]
