# Generated by Django 3.0.3 on 2020-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0019_auto_20200410_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='latitude',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='temp',
            name='longitude',
            field=models.FloatField(default=1.0),
        ),
    ]
