# Generated by Django 3.0.3 on 2020-04-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0020_auto_20200411_1122'),
        ('waterlogged', '0021_auto_20200410_1820'),
    ]

    operations = [
    ]
