# Generated by Django 3.0.3 on 2020-04-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0022_merge_20200411_1639'),
        ('waterlogged', '0023_auto_20200411_2035'),
    ]

    operations = [
    ]
