# Generated by Django 3.0.3 on 2020-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0026_profile_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Maps_URL',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='image',
            name='user_id_of_upload',
            field=models.IntegerField(default=0),
        ),
    ]
