# Generated by Django 3.0.3 on 2020-04-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterlogged', '0027_auto_20200419_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pre',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
